---
development:
  SESSION_SECRET: ''
  MSG_KEY: ''
  SENDGRID_DOMAIN: ''
  SENDGRID_USERNAME: ''
  SENDGRID_PASSWORD: ''
  REDIS_URL: ''
  GH_CLIENT_ID: ''
  GH_CLIENT_SECRET: ''

test:
  SESSION_SECRET: ''
  MSG_KEY: ''
  SENDGRID_DOMAIN: ''
  SENDGRID_USERNAME: ''
  SENDGRID_PASSWORD: ''
  REDIS_URL: ''
  GH_CLIENT_ID: ''
  GH_CLIENT_SECRET: ''
